# Prepare the generated official MIG example as the durable hardware-test XPR.
set script_dir [file dirname [file normalize [info script]]]
set project_file [file join $script_dir SP701_DDR3_Memory_Test.xpr]
set source_dir [file join $script_dir src official_mig_example]
set generated_imports [file join $script_dir _staging mig_example mig_7series_0_ex imports]
set wrapper_file [file join $script_dir src sp701_ddr3_memory_test_top.v]
set board_xdc [file join $script_dir constraints sp701_reset.xdc]
set evidence_dir [file normalize [file join $script_dir .. .. .. docs M11 evidence ddr3-hardware-test-2026-10-02]]

if {![file exists $project_file]} { error "Missing generated MIG example XPR: $project_file" }
if {![file exists [file join $source_dir example_top.v]]} {
  # MIG example RTL is generated by the installed Vivado IP and intentionally
  # not tracked. Restore only the synthesis inputs from the local example.
  file mkdir $source_dir
  foreach name [list \
    example_top.v mig_7series_v4_2_axi4_tg.v \
    mig_7series_v4_2_axi4_wrapper.v mig_7series_v4_2_cmd_prbs_gen_axi.v \
    mig_7series_v4_2_data_gen_chk.v mig_7series_v4_2_tg.v example_top.xdc] {
    set source [file join $generated_imports $name]
    if {![file exists $source]} { error "Missing Vivado MIG example source: $source" }
    file copy -force $source [file join $source_dir $name]
  }
}
open_project $project_file
set_property part xc7s100fgga676-2 [current_project]
set_property board_part xilinx.com:sp701:part0:1.0 [current_project]

# Replace generator-staging paths with local project source paths. These
# vendor-generated files are copied from this Vivado installation by the
# generation flow and are locally ignored; the XPR and recreation flow remain
# tracked. No MIG-generated RTL or constraints are edited.
foreach f [get_files -quiet -of_objects [get_filesets sources_1]] {
  if {[string first "/_staging/mig_example/" [file normalize $f]] >= 0} {
    remove_files $f
  }
}
foreach f [get_files -quiet -of_objects [get_filesets constrs_1]] {
  if {[string first "/_staging/mig_example/" [file normalize $f]] >= 0} {
    remove_files $f
  }
}

set rtl_files [list \
  [file join $source_dir mig_7series_v4_2_axi4_tg.v] \
  [file join $source_dir mig_7series_v4_2_axi4_wrapper.v] \
  [file join $source_dir mig_7series_v4_2_cmd_prbs_gen_axi.v] \
  [file join $source_dir mig_7series_v4_2_data_gen_chk.v] \
  [file join $source_dir mig_7series_v4_2_tg.v] \
  [file join $source_dir example_top.v] \
  $wrapper_file]
add_files -norecurse $rtl_files
add_files -fileset constrs_1 -norecurse [file join $source_dir example_top.xdc]
add_files -fileset constrs_1 -norecurse $board_xdc
set_property top SP701_DDR3_Memory_Test [get_filesets sources_1]
update_compile_order -fileset sources_1

if {[llength [get_ips ila_0 -quiet]] == 0} {
  create_ip -vendor xilinx.com -library ip -name ila -version 6.2 -module_name ila_0
}
set ila [get_ips ila_0]
set_property -dict [list \
  CONFIG.C_NUM_OF_PROBES {7} \
  CONFIG.C_PROBE0_WIDTH {1} \
  CONFIG.C_PROBE1_WIDTH {1} \
  CONFIG.C_PROBE2_WIDTH {32} \
  CONFIG.C_PROBE3_WIDTH {32} \
  CONFIG.C_PROBE4_WIDTH {1} \
  CONFIG.C_PROBE5_WIDTH {1} \
  CONFIG.C_PROBE6_WIDTH {1} \
  CONFIG.C_DATA_DEPTH {1024}] $ila
generate_target all $ila
if {[llength [get_runs ila_0_synth_1 -quiet]] == 0} { create_ip_run $ila }
report_ip_status -file [file join $evidence_dir ip-status.rpt]
puts "DDR_PROJECT=[get_property DIRECTORY [current_project]]/[get_property NAME [current_project]].xpr"
puts "DDR_BOARD=[get_property BOARD_PART [current_project]]"
puts "DDR_PART=[get_property PART [current_project]]"
puts "DDR_IP_LOCKED=[get_property IS_LOCKED $ila]"
puts "DDR_TOP=[get_property TOP [get_filesets sources_1]]"
puts "DDR_RTL_COUNT=[llength [get_files -of_objects [get_filesets sources_1]]]"
puts "DDR_CONSTRAINTS=[get_files -of_objects [get_filesets constrs_1]]"
close_project
exit
